# Generated by Django 5.1.1 on 2024-10-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_alter_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='canton',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
