# Generated by Django 5.1.1 on 2024-10-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_property_canton_property_country_property_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
