# Generated by Django 5.1.1 on 2024-10-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_property_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Granero', 'Granero'), ('Bed & breakfast', 'Bed & breakfast'), ('Barco', 'Barco'), ('Cabañas', 'Cabañas'), ('Casa rodante', 'Casa rodante'), ('Casa particular', 'Casa particular'), ('Castillo', 'Castillo'), ('Cueva', 'Cueva'), ('Contenedores', 'Contenedores'), ('Casa cíclada', 'Casa cíclada'), ('Dammuso', 'Dammuso'), ('Domo', 'Domo'), ('Casa ecológica', 'Casa ecológica'), ('Granja', 'Granja'), ('Casa de huéspedes', 'Casa de huéspedes'), ('Hotel', 'Hotel'), ('Casa flotante', 'Casa flotante'), ('Kezhan', 'Kezhan'), ('Minsu', 'Minsu'), ('Riad', 'Riad'), ('Ryokan', 'Ryokan'), ('Casa de pastor', 'Casa de pastor'), ('Tienda de campo', 'Tienda de campo'), ('Minicasa', 'Minicasa'), ('Torre', 'Torre'), ('Casa del árbol', 'Casa del árbol'), ('Trullo', 'Trullo'), ('Molino de viento', 'Molino de viento'), ('Yurta', 'Yurta')], max_length=100),
        ),
    ]
