# Generated by Django 5.1.1 on 2024-10-26 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Granero', 'Granero'), ('Bed & breakfast', 'Bed & breakfast'), ('Barco', 'Barco'), ('Cabañas', 'Cabañas'), ('Casa rodante', 'Casa rodante'), ('Castillo', 'Castillo'), ('Cueva', 'Cueva'), ('Contenedores', 'Contenedores'), ('Casa cíclada', 'Casa cíclada'), ('Dammuso', 'Dammuso'), ('Domo', 'Domo'), ('Casa ecológica', 'Casa ecológica'), ('Granja', 'Granja'), ('Casa de huéspedes', 'Casa de huéspedes'), ('Hotel', 'Hotel'), ('Casa flotante', 'Casa flotante'), ('Kezhan', 'Kezhan'), ('Minsu', 'Minsu'), ('Riad', 'Riad'), ('Ryokan', 'Ryokan'), ('Casa de pastor', 'Casa de pastor'), ('Tienda de campo', 'Tienda de campo'), ('Minicasa', 'Minicasa'), ('Torre', 'Torre'), ('Casa del árbol', 'Casa del árbol'), ('Trullo', 'Trullo'), ('Molino de viento', 'Molino de viento'), ('Yurta', 'Yurta')], max_length=100),
        ),
    ]
