# Generated by Django 5.2.5 on 2025-08-22 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_order_number_customer_tipo_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('signature_field', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_date', models.DateField(blank=True, null=True)),
                ('packed_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='api.order')),
            ],
            options={
                'indexes': [models.Index(fields=['invoice_number'], name='api_invoice_invoice_59a3b3_idx'), models.Index(fields=['order'], name='api_invoice_order_i_a23847_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('partial', 'Partial'), ('full', 'Full')], default='partial', max_length=20)),
                ('reference_document', models.FileField(blank=True, null=True, upload_to='payment_references/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'payment_date'], name='api_payment_order_i_650e7e_idx')],
            },
        ),
    ]
