# Generated by Django 4.2.7 on 2023-12-11 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_remove_lead_comments_lead_avoidable_graphic_elements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='comments',
            field=models.ManyToManyField(related_name='lead_comments', through='api.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
