# Generated by Django 5.2.5 on 2025-08-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invoice_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='variaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpoints',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tag'),
        ),
    ]
