# Generated by Django 5.2.5 on 2025-08-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tag_player_observaciones_player_variaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pedido_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
