# Generated by Django 4.2.7 on 2023-12-11 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_lead_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='lead_comments', through='api.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('ganado', 'Ganado')], default='new', max_length=10, null=True),
        ),
    ]
