# Generated by Django 4.2.7 on 2023-12-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_lead_comments_alter_lead_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='comercial_activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
