# Generated by Django 5.2.5 on 2025-11-03 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_pedido_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionqueue',
            options={'ordering': ['delivery_date', 'queue_type', 'position']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='design_confirmation_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_50_date',
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Solo para pagos', max_digits=10),
        ),
        migrations.AddField(
            model_name='productionqueue',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgente'), ('express', 'Express'), ('personalizado', 'Personalizado')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='pedido_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('design_pending', 'Diseño Pendiente'), ('design_confirmed', 'Diseño Confirmado'), ('completed', 'Completado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('payment', 'Pago / Abono'), ('design_approved', 'Diseño Aprobado'), ('delivered', 'Entregado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productionqueue',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AlterField(
            model_name='productionqueue',
            name='queue_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgente'), ('express', 'Express'), ('personalizado', 'Personalizado')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='productionqueue',
            unique_together={('queue_type', 'delivery_date', 'position')},
        ),
    ]
