# Generated by Django 5.2.5 on 2025-11-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_order_paid_amount_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Solo para pagos', max_digits=10),
        ),
    ]
