# Generated by Django 4.2.7 on 2024-02-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userprofile_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_status',
            field=models.CharField(choices=[('customer', 'Customer'), ('user', 'User'), ('administrator', 'Administrator'), ('sales', 'Sales'), ('design', 'Design')], default='customer', max_length=20),
        ),
    ]
