# Generated by Django 5.2.5 on 2025-11-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_paid_amount_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='api_invoice_invoice_59a3b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='api_invoice_order_i_a23847_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='api_payment_order_i_650e7e_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
