# Generated by Django 5.2.5 on 2025-11-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_invoice_api_invoice_invoice_59a3b3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('payment', 'Pago / Abono'), ('payment_50_confirmed', '50% Pago Recibido'), ('design_approved', 'Diseño Aprobado'), ('delivered', 'Entregado')], max_length=50),
        ),
    ]
