# Generated by Django 4.2.7 on 2024-02-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_address_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_status',
            field=models.CharField(choices=[('customer', 'Customer'), ('user', 'User'), ('administrator', 'Administrator'), ('sales', 'Sales'), ('design', 'Design'), ('supervisor', 'Supervisor')], default='customer', max_length=20),
        ),
    ]
