# Generated by Django 5.1.1 on 2024-09-20 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userprofile_staff_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='avoidable_graphic_elements',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='facebook_comment',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='fan_page_category',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='fan_page_comments',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='fan_page_information_details',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='industry_leaders',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='logo_and_visual_identity_communication',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='logo_applications',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='market_positioning_strategy',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='preferred_brands_references',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='preferred_color_palette',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='primary_logo_usage',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='products_or_services',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='project_objective',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='purchase_behavior',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='symbol_or_icon_preference',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='unique_value_proposition',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='visual_identity_communication',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='visual_identity_goals',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='whatsapp_details',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='wsb_phone_number',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='wsb_predefined_message',
        ),
        migrations.AlterField(
            model_name='lead',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='lead_comments', through='api.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('ganado', 'Ganado')], default='nuevo', max_length=10, null=True),
        ),
    ]
