# Generated by Django 5.2.5 on 2025-11-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_orderevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points_per_amount', models.PositiveIntegerField(default=10)),
                ('amount_threshold', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='customerpoints',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerpoints',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('payment', 'Pago / Abono'), ('payment_50_confirmed', '50% Pago Recibido'), ('payment_100_confirmed', '100% Pago Recibido'), ('design_approved', 'Diseño Aprobado'), ('delivered', 'Entregado')], max_length=50),
        ),
        migrations.AddField(
            model_name='customerpoints',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pointsconfig'),
        ),
    ]
