# Generated by Django 5.2.5 on 2025-11-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pointsconfig_customerpoints_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsconfig',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Configuración predeterminada para todas las órdenes'),
        ),
        migrations.AddConstraint(
            model_name='pointsconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_points_config'),
        ),
    ]
