# Generated by Django 5.1.1 on 2024-10-22 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_userprofile_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
