# Generated by Django 5.1.1 on 2024-10-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_workexperience_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
