# Generated by Django 5.1.1 on 2024-10-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_workexperience_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
