# Generated by Django 5.1.1 on 2024-10-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_lead_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='openwork',
            field=models.BooleanField(default=False),
        ),
    ]
