# Generated by Django 5.1.1 on 2024-12-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_userprofile_openwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(default='N/A', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
