# Generated by Django 5.1.1 on 2024-12-13 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userprofile_id_number_userprofile_id_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='comercial_activity',
            new_name='commercial_activity',
        ),
    ]
