# Generated by Django 5.1.1 on 2025-05-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_lead_brand_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='target_gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
