# Generated by Django 5.1.1 on 2024-09-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_jobapplication_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobQuestion',
        ),
    ]
