# Generated by Django 5.1.1 on 2024-09-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_delete_jobquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobalert',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
