# Generated by Django 5.1.1 on 2024-09-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_jobalert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobalert',
            name='skills_required',
            field=models.ManyToManyField(blank=True, to='employee.skill'),
        ),
    ]
