# Generated by Django 5.1.1 on 2024-09-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_jobalert_skills_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobalert',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='jobalert',
            name='skills_required',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
