# Generated by Django 5.1.1 on 2024-09-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_jobalert_skills_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobalert',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='jobalert',
            name='skills_required',
            field=models.ManyToManyField(blank=True, to='employee.skill'),
        ),
    ]
