# Generated by Django 5.1.1 on 2024-10-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_jobalert_skills_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='subcategory',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
