# Generated by Django 5.1.1 on 2024-10-08 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_jobposting_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='subcategory',
        ),
    ]
