# Generated by Django 4.2.7 on 2024-02-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='comercial_activity',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
