# Generated by Django 5.1.1 on 2024-09-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_comercial_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='comercial_activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
