# Generated by Django 4.2.7 on 2023-12-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='newspost',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
