# Generated by Django 4.2.7 on 2023-12-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_newspost_phone_number_newspost_url_newspost_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='content_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('pdf', 'PDF'), ('video', 'Video')], max_length=10, null=True),
        ),
    ]
