# Generated by Django 4.2.7 on 2023-12-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_newspost_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='content_type',
            field=models.CharField(blank=True, choices=[('clasificado', 'Clasificado'), ('clasificado_logo', 'Clasificado_logo'), ('clasificado_imagen', 'Clasificado_imagen')], max_length=100, null=True),
        ),
    ]
