# Generated by Django 4.2.7 on 2024-02-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='subsubcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
