# Generated by Django 5.1.1 on 2024-12-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_distributor_canton_distributor_comercial_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
