# Generated by Django 5.1.1 on 2025-07-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='daily_production_capacity',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
