# Generated by Django 4.2.7 on 2024-02-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_service_table_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
