# Generated by Django 4.2.7 on 2024-02-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_service_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
