# Generated by Django 4.2.7 on 2024-02-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_combo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='pay_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
