# Generated by Django 5.1.1 on 2024-09-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_subproduct_pay_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='code',
            field=models.CharField(default='AB00000', max_length=7, unique=True),
        ),
    ]
