# Generated by Django 5.1.1 on 2024-09-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_combo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
