# Generated by Django 5.1.1 on 2024-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_combo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='code',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
