# Generated by Django 5.1.1 on 2024-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_combo_code_alter_combo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
