# Generated by Django 5.1.1 on 2024-09-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_combo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='code',
            field=models.CharField(default='AB00000', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
