# Generated by Django 5.1.1 on 2024-09-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_combo_code_alter_combo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=100, null=True),
        ),
    ]
