# Generated by Django 5.1.1 on 2024-10-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='subcategory',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='subsubcategory',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
