# Generated by Django 5.1.1 on 2025-01-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_subproduct_subcategory_subproduct_subsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coupons/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_members/')),
            ],
        ),
        migrations.AddField(
            model_name='subproduct',
            name='certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='business_hours',
            field=models.ManyToManyField(blank=True, related_name='subproducts', to='products.businesshour'),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='coupons',
            field=models.ManyToManyField(blank=True, related_name='subproducts', to='products.coupon'),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='subproducts', to='products.teammember'),
        ),
    ]
