# Generated by Django 5.1.1 on 2025-01-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_businesshour_coupon_teammember_subproduct_certified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
