# Generated by Django 5.1.1 on 2025-01-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_coupon_code_alter_coupon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshour',
            name='day',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], max_length=10),
        ),
    ]
