# Generated by Django 5.1.1 on 2025-03-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_businesshour_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=100, null=True),
        ),
    ]
