# Generated by Django 5.1.1 on 2025-05-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_subproduct_business_hours_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_name_2d995b_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_country_6daf9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_provinc_7d6fb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_canton_0ccdcd_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_distrit_f03e2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_comerci_c8e567_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_email_1f2ce3_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_phone_n_feeb83_idx',
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='business_hours',
            field=models.ManyToManyField(blank=True, related_name='subproducts', to='products.businesshour'),
        ),
    ]
