# Generated by Django 5.1.1 on 2025-05-01 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_subproduct_products_su_name_2d995b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='characteristic',
            index=models.Index(fields=['name'], name='products_ch_name_33bcf3_idx'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['name'], name='products_co_name_c802aa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='products_se_name_338c08_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['subproduct'], name='products_se_subprod_61f927_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['name'], name='products_su_name_2d995b_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['country'], name='products_su_country_6daf9c_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['province'], name='products_su_provinc_7d6fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['canton'], name='products_su_canton_0ccdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['distrito'], name='products_su_distrit_f03e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['comercial_activity'], name='products_su_comerci_c8e567_idx'),
        ),
    ]
