# Generated by Django 5.1.1 on 2025-05-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_characteristic_products_ch_name_33bcf3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='characteristic',
            name='products_ch_name_33bcf3_idx',
        ),
        migrations.RemoveIndex(
            model_name='combo',
            name='products_co_name_c802aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_name_9ff0a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='products_se_name_338c08_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='products_se_subprod_61f927_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_name_2d995b_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_country_6daf9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_provinc_7d6fb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_canton_0ccdcd_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_distrit_f03e2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_comerci_c8e567_idx',
        ),
    ]
