# Generated by Django 5.1.1 on 2025-05-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_characteristic_products_ch_name_33bcf3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='name',
        ),
    ]
