# Generated by Django 5.1.1 on 2025-05-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_coupon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
