# Generated by Django 5.1.1 on 2025-05-12 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_coupon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='subproduct',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.subproduct'),
        ),
    ]
