# Generated by Django 5.1.1 on 2025-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_combo_subproduct'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['name'], name='products_su_name_2d995b_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['email'], name='products_su_email_1f2ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['country'], name='products_su_country_6daf9c_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['province'], name='products_su_provinc_7d6fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['canton'], name='products_su_canton_0ccdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['distrito'], name='products_su_distrit_f03e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['comercial_activity'], name='products_su_comerci_c8e567_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['subcategory'], name='products_su_subcate_f46d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['subsubcategory'], name='products_su_subsubc_3a10a9_idx'),
        ),
    ]
