# Generated by Django 5.1.1 on 2025-05-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_subproduct_products_su_name_2d995b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_name_2d995b_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_email_1f2ce3_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_country_6daf9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_provinc_7d6fb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_canton_0ccdcd_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_distrit_f03e2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_comerci_c8e567_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_subcate_f46d1a_idx',
        ),
        migrations.RemoveIndex(
            model_name='subproduct',
            name='products_su_subsubc_3a10a9_idx',
        ),
    ]
