# Generated by Django 5.1.1 on 2025-05-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_subproduct_products_su_name_2d995b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='point_of_sale',
            field=models.BooleanField(default=False),
        ),
    ]
