# Generated by Django 5.1.1 on 2025-05-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_subproduct_point_of_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='subcategory',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='subsubcategory',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
