# Generated by Django 5.1.1 on 2025-05-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_subproduct_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='subcategory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='subsubcategory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
